name: Build and Test Dart
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Dart
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang libgtk-3-dev

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.23'

      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 #v2.16.0
        with:
          flutter-version: '3.22.3'

      - name: Check out source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Go generate
        working-directory: ./bruig
        run: go generate ./golibbuilder

      - name: Linux GUI build
        working-directory: ./bruig/flutterui/bruig
        run: flutter build linux
